spring.application.name=cardapio
spring.profiles.active=prod
amazon.aws.region=us-east-1
dynamodb.table.name=${DYNAMODB_TABLE_NAME:Pedidos}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
aws.ses.sender=rodrigo.spoo@gmail.com

# Habilita os endpoints do Actuator para o Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB