AWS_REGION=sa-east-1
AWS_ACCESS_KEY_ID=fake-key
AWS_SECRET_ACCESS_KEY=fake-secret
AWS_SQS_URL=http://localhost:4566
AWS_SQS_RESULT_URL=http://localhost:4566
# Adicione outras propriedades que você usa no @Value